### ISSUE TITLE
Theme Conflict Fix with ClearVision V7 - PingNotification

### ISSUE THREAD

**Issue by Fynn9563** [DaddyBoard/BD-Plugins#29]
Hey!  
I noticed that the plugin was causing some layout issues with the **ClearVision V7** theme. Specifically, this line:

```css
div#app-mount > div > div > div > div {
    transform: translate(0);
}
```

…was interfering with some of the theme's transforms and breaking parts of the UI.

I tried removing that line and just added this instead:

```css
.ping-notification {
    position: fixed !important;
    z-index: 999999 !important;
    pointer-events: auto !important;
}
```

That seemed to fix the overlap issue for me without affecting functionality — at least in my setup.  
Not sure if this is the best way, but figured I’d share in case it’s helpful!

Thanks for all your work on this plugin — it’s really great. 🙏
